---
title: "R Notebook"
output: html_notebook
---
### ANOVA TWO WAY
# 1.Ler dados
# 2.Balanceamento
# 3.distribuicao normal
# 4.homocedasticidade
# 5.ANOVA
# 6.Residuos
# 7. Conclua. Post hoc?
# 8. TukeyHSD


```{r import_dataset, echo=FALSE, results="hide", include=FALSE, eval=FALSE}
library(readr)
suppressMessages(dados <- read_csv("wspc_rlang/dataset/dados_Hair_etal.csv"))
```

```{r dataset}
dados$size
dados$use
dados$type
```


```{r balanceamento}
table (dados$size, dados$type)
chisq.test(table (dados$size, dados$type)) # testando se esta desbalanceado
# Resultado significativo . Logo , as frequesncias soa desbalanceadas 
# O que fazer selecionar aleatoriamente 40 dos 60 small
# Dessa maneira, os dados ficam desbalanceados
# Outra alternativa: fazer  outro teste (teste t seria uma boa alternativa)  t.test(use ~ size, dados)
```

```{r distribuicao_normal}
result <- tapply( X = dados$use, INDEX= dados$size, FUN = shapiro.test)
for (i in result){
    print (i)
}
result <- tapply( X = dados$use, INDEX= dados$type, FUN = shapiro.test)
for (i in result){
    print (i)
}
```


```{r homocedasticidade}
tapply( X = dados$use, INDEX= dados$type, FUN = var) # vendo os valores entre  os grupos e possivel ver que nao ha uma diferenca significativa entre as variancias
tapply( X = dados$use, INDEX= dados$size, FUN = var) # vendo os valores entre  os grupos e possivel ver que nao ha uma diferenca significativa entre as variancias
bartlett.test(use ~ size, dados) # dados sao homocedasticos
bartlett.test(use ~ type, dados) # dados sao homocedasticos
```

```{r ANOVA}
result <- aov (use ~size*type, dados) # mesma coisa
result <- aov (use ~size+type+size:type, dados) # mesma coisa
summary(result)
```

```{r residuos}
plot(result, which = 1)
plot(result, which = 2)

residuals(result)

shapiro.test(residuals(result)) 
mean(residuals(result))
```

```{r conclua}
paste ("resultado significativo, as medias sao diferentes e podemos executar um teste de post hoc.")
paste ("Obs: so existem 2 grupos entao tecnicamente o teste sao dispensaveis")
```


```{r post_hoc}
plot(TukeyHSD(result)) # somente e necessario quando temos mais de 2 grupos para fazer 
```
