---
title: "Regressao Logistica"
author: "Leandro Sampaio"
date: "August 18, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressMessages(if(!require(AER)){install.packages("AER")})
```

```{r}
data (Affairs, package = "AER"); affairs = Affairs;summary(affairs)

str(affairs)
```


```{r}
mod = lm(rating~education,affairs); summary(mod)
```

```{r}
affairs$ynaffairs <- NULL
affairs$ynaffairs[affairs$affairs > 0] <- 1
affairs$ynaffairs[affairs$affairs == 0] <- 0
str (affairs$ynaffairs)
affairs$ynaffairs <- factor(affairs$ynaffairs, 
                            levels = c(0,1), 
                            labels = c("no","yes"))
str (affairs$ynaffairs)
table(affairs$ynaffairs)
```

```{r}
mod.full = glm( data = affairs, family = binomial(link = "logit") ,
           ynaffairs ~ gender + age + yearsmarried + children + religiousness + education + occupation + rating)
summary(mod.full)
```

```{r}
mod.partial = glm( data = affairs, family = binomial(link = "logit") ,
           ynaffairs ~ age + yearsmarried + religiousness +  rating)
summary(mod.partial)
```

```{r}
anova(mod.full,mod.partial, test = 'Chisq') # modelos equivalentes  Pr(<Chi)=0.2108
exp(coef(mod.partial))
```
```{r}
testdata <- data.frame( rating = c (1,2,3,4,5), 
                        age = mean (affairs$age), 
                        yearsmarried = mean (affairs$yearsmarried),
                        religiousness =  mean(affairs$religiousness)
                        ); testdata

testdata$prob <- predict(mod.partial, newdata =  testdata, type = "response"); testdata

testdata <- data.frame( rating = mean (affairs$rating), 
                        age = mean (affairs$age), 
                        yearsmarried = mean (affairs$yearsmarried),
                        religiousness =  c(1,2,3,4,5)
                        ); testdata

testdata$prob <- predict(mod.partial, newdata =  testdata, type = "response"); testdata

testdata <- data.frame( rating = mean (affairs$rating), 
                        age = mean (affairs$age), 
                        yearsmarried = mean (affairs$yearsmarried),
                        religiousness =  c(1,2,3,4,5)
                        ); testdata

testdata$prob <- predict(mod.partial, newdata =  testdata, type = "response"); testdata

mod.partial_ocuppation = glm( data = affairs, family = binomial(link = "logit") ,
           ynaffairs ~ age + yearsmarried + religiousness +  rating + occupation)

testdata_occupation <- data.frame( rating = mean (affairs$rating), 
                        age = mean (affairs$age), 
                        yearsmarried = mean (affairs$yearsmarried),
                        religiousness =  c(1,2,3,4,5),
                        occupation = mean (affairs$occupation) 
                        );
testdata_occupation$prob <- predict(mod.partial_ocuppation, newdata =  testdata_occupation, type = "response"); testdata_occupation

```

```{r}
testdata_occupation$prob <- predict(mod.partial_ocuppation, newdata =  testdata_occupation, type = "response"); testdata_occupation

testdata_occupation <- data.frame( rating = mean (affairs$rating), 
                        age = mean (affairs$age), 
                        yearsmarried = mean (affairs$yearsmarried),
                        religiousness =  mean (affairs$religiousness),
                        occupation = c(1,2,3,4,5,6,7)
                        ); testdata

testdata$prob <- predict(mod.partial_ocuppation, newdata =  testdata, type = "response"); testdata
```